/*
 * ConnectFrame.java
 *
 * Created on December 8, 2007, 1:18 PM
 */

package go_client;
import java.io.IOException;
import javax.swing.JOptionPane;
import go_server.GoServer;
import java.net.InetAddress;
import java.net.UnknownHostException;

/**
 * The Connection frame creates the client and possibly a server if the 
 * user wants to host a game.
 * @author mike, cj
 */
public class ConnectFrame extends javax.swing.JFrame {
    
    /** Creates new form ConnectFrame */
    public ConnectFrame() {
        initComponents();
        this.setVisible(true);
    }
    
    /**
     * Sets the <B>BoardUI</B> to a new one
     * @param board the new board
     */
    public void setBoardUI(BoardUI board)
    {
        this.board = board;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        hostGroup = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hostText = new javax.swing.JTextField();
        portText = new javax.swing.JTextField();
        hostRadBtn = new javax.swing.JRadioButton();
        connectRadBtn = new javax.swing.JRadioButton();
        nameText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Connection");
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Host IP Address");

        jLabel2.setText("Host Port Number");

        hostText.setEditable(false);

        portText.setText("4444");

        hostGroup.add(hostRadBtn);
        hostRadBtn.setSelected(true);
        hostRadBtn.setText("Host Game");
        hostRadBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        hostRadBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        hostRadBtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                hostRadBtnItemStateChanged(evt);
            }
        });

        hostGroup.add(connectRadBtn);
        connectRadBtn.setText("Connect To Server");
        connectRadBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        connectRadBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel3.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(hostRadBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(152, 152, 152))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nameText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                .addComponent(portText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                .addComponent(hostText, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                            .addGap(65, 65, 65)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(connectRadBtn)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hostRadBtn)
                    .addComponent(connectRadBtn))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(hostText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(portText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hostRadBtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_hostRadBtnItemStateChanged
        hostText.setEditable(!hostText.isEditable());
    }//GEN-LAST:event_hostRadBtnItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            int port = new Integer(portText.getText());
            String host = hostText.getText();
            if(hostRadBtn.isSelected())
            {
                board.initServer(port);
                host = "localhost";
            }
            board.initClient(host, port);
            if(nameText.getText().isEmpty())
            {
                board.setPlayerName(InetAddress.getLocalHost().getHostAddress());
            }
            else 
                board.setPlayerName(nameText.getText());
            this.dispose();   
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Bad Port Number. Must be an Integer.");
        }
        catch(UnknownHostException uE)
        {
            board.display("***Hostname unresolved");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
 /*   public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConnectFrame().setVisible(true);
            }
        });
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton connectRadBtn;
    private javax.swing.ButtonGroup hostGroup;
    private javax.swing.JRadioButton hostRadBtn;
    private javax.swing.JTextField hostText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField portText;
    // End of variables declaration//GEN-END:variables
    
    private BoardUI board;
}
