/*
 * NewGameFrame.java
 *
 * Created on November 6, 2007, 8:29 PM
 */

package go_client;
import go.GameQuery;
import java.awt.Dimension;
/**
 * The frame that creates a new instance of <B>Game</B>
 * @author Caldwell Bailey
 */
public class NewGameFrame extends javax.swing.JFrame {
    
    /** Creates new form NewGameFrame */
    public NewGameFrame() {
        initComponents();
        this.setVisible(true);
    }
    /**
     * Sets the <B>BoardUI</b> contained in this class to the parameter
     * @param board the new BoardUI
     */
    public void setBoardUI(BoardUI board)
    {
        this.boardUI = board;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        boardSizeLabel = new javax.swing.JLabel();
        sizeBox = new javax.swing.JComboBox();
        buttonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Game");
        setAlwaysOnTop(true);
        boardSizeLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        boardSizeLabel.setText("Board Size");

        sizeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "19 x 19", "5 x 5", "9x9", "13 x 13 ", "15 x 15" }));
        sizeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeBoxActionPerformed(evt);
            }
        });

        buttonOK.setText("OK");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(boardSizeLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 77, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(sizeBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(51, 51, 51)
                        .add(buttonOK)))
                .add(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(boardSizeLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(sizeBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(buttonOK)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sizeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeBoxActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_sizeBoxActionPerformed

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        int index = sizeBox.getSelectedIndex();
        int size = 19;
        if(index == 0)
            size = 19;
        else if(index == 1)
            size = 5;
        else if(index == 2)
            size = 9;
        else if(index == 3)
            size = 13;
        else if(index == 4)
            size = 15;
        else
            boardUI.display("shenanigans");
        
        GameQuery newGame = new GameQuery(size);
        boardUI.sendToClient(newGame);
        boardUI.display("***Waiting for opponent's response...");
        boardUI.clearLabels();
        this.dispose();
    }//GEN-LAST:event_buttonOKActionPerformed
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NewGameFrame().setVisible(true);
//            }
//        });
//    }
    
    private BoardUI boardUI;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boardSizeLabel;
    private javax.swing.JButton buttonOK;
    private javax.swing.JComboBox sizeBox;
    // End of variables declaration//GEN-END:variables
    
}
